version: "3.3"

volumes:
  redis-data:
  postgres-data:
  bundle-data:
  node-data:

services:
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: scorecard_admin
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: scorecard_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    logging: &logging
      options:
        max-size: "200k"
        max-file: "10"

  redis:
    image: redis:5.0.5-alpine
    command: redis-server
    volumes:
      - redis-data:/data
    logging:
      driver: none

  website: &webapp
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.docker
    working_dir: /home/app/scorecard
    volumes:
      - .:/home/app/scorecard
      - bundle-data:/home/app/scorecard/vendor/bundle
      - node-data:/home/app/scorecard/node_modules
    ports:
      - ${DOCKER_WEBSITE_PORT:-80}:3000
      - 9630:9630
      - 9000:9000
      - 3035:3035
    tty: true
    stdin_open: true
    command: bash -c 'rm -f .overmind.sock && overmind start -c web,css,js'
    logging:
      <<: *logging
